In [1]:
import numpy as np

import astropy.units as u
from astropy.time import Time
from astropy.coordinates import solar_system_ephemeris

from poliastro.bodies import Sun,Venus, Earth, Jupiter, Saturn
from poliastro.twobody import Orbit
from poliastro.maneuver import Maneuver
from poliastro.iod import izzo
from poliastro.plotting import OrbitPlotter2D
from poliastro.util import norm

from scipy import optimize as opt
 
solar_system_ephemeris.set("jpl")

<ScienceState solar_system_ephemeris: 'jpl'>

In [13]:
cassini_venus2 = Time("1999-06-24")
cassini_earth2 = Time("1999-08-18")
cassini_jupiter = Time("2000-12-30")
cassini_saturn = Time("2004-07-01")

#cassini transit
cassini_js_time = cassini_saturn-cassini_jupiter
cassini_ej_time = cassini_jupiter-cassini_earth2
cassini_ve_time = cassini_earth2-cassini_venus2

In [32]:
tmod=[0,0,0,0]
plot_on=0;

def trajectory_calculator(t=[0,0,0,0],plot_on=0,disp_on=0):
    #start with cassini style assumptions
    cassini_venus2 = Time("1999-06-24")
    cassini_earth2 = Time("1999-08-18")
    cassini_jupiter = Time("2000-12-30")
    cassini_saturn = Time("2004-07-01")

    #cassini transit
    cassini_js_time = cassini_saturn-cassini_jupiter
    cassini_ej_time = cassini_jupiter-cassini_earth2
    cassini_ve_time = cassini_earth2-cassini_venus2


    tmod_s  = t[0] #arrival time in saturn relative to 2020
    tmod_js = t[1] #transit times
    tmod_ej = t[2] 
    tmod_ve = t[3]


    time_js = tmod_js*u.year
    time_ej = tmod_ej*u.year
    time_ve = tmod_ve*u.year

    date_arrive_saturn = Time("2020-01-01", scale="utc")+tmod_s*u.year;


    #create target orbit
    o_sf = Orbit.from_body_ephem(Saturn, date_arrive_saturn)
    r_sf, v_sf = o_sf.rv()
    #o_sf.plot()
    if disp_on:
        print('computed saturn')

    ################## Jupiter ################## 

    #guess flyby date of Jupiter
    date_flyby_jupiter = date_arrive_saturn-time_js

    #construct j orbit
    o_j = Orbit.from_body_ephem(Jupiter, date_flyby_jupiter)
    #o_j.plot()

    #compute transfer lambert trajectory
    (v_jo, v_si), = izzo.lambert(Sun.k, o_j.r, o_sf.r, time_js)
    trx_js = Orbit.from_vectors(Sun, o_j.r, v_jo, epoch=date_flyby_jupiter)
    #trx_js.plot()
    if disp_on:
        print('computed J-S')
    ################## Earth ################## 
    #guess flyby date of Earth
    date_flyby_earth = date_arrive_saturn-time_js-time_ej

    #construct j orbit
    o_e2 = Orbit.from_body_ephem(Earth, date_flyby_earth)
    #o_e2.plot()

    #compute transfer lambert trajectory
    (v_eo, v_ji), = izzo.lambert(Sun.k, o_e2.r, o_j.r, time_ej)
    trx_ej = Orbit.from_vectors(Sun, o_e2.r, v_eo, epoch=date_flyby_earth)
    #trx_ej.plot()
    if disp_on:
        print('computed E-J')                            

    ################## Venus2 ################## 
    #guess flyby date of Venus2
    date_flyby_venus2 = date_arrive_saturn-time_js-time_ej-time_ve

    #construct j orbit
    o_v2 = Orbit.from_body_ephem(Venus, date_flyby_venus2)
    #o_v2.plot()

    #compute transfer lambert trajectory
    (v_v2o, v_ei), = izzo.lambert(Sun.k, o_v2.r, o_e2.r, time_ve)
    trx_v2e = Orbit.from_vectors(Sun, o_v2.r, v_v2o, epoch=date_flyby_venus2)
    #trx_v2e.plot()    
    if disp_on:
        print('computed V-E')                            

    ################## Sum delta v ##################                             
    delv_e = norm(v_eo-v_ei)
    delv_j = norm(v_jo-v_ji)
    delv_s = norm(v_si-v_sf)

    total_deltav=sum([delv_e,delv_j,delv_s]) 

    if disp_on:
        print('Total delta-v: ', total_deltav)

    ################## Plot ##################  

    if plot_on:
        op = OrbitPlotter2D()

        op.plot(o_v2,label="Venus2 Orbit")
        op.plot(o_e2,label="Earth2 Orbit")
        op.plot(o_j, label="Jupiter Orbit")
        op.plot(o_sf, label="Saturn Orbit")


        op.plot(trx_v2e, label="V2-E")
        op.plot(trx_ej, label="E-J")
        op.plot(trx_js, label="J-S")
        
    orbits = (o_v2,o_e2,o_j,o_sf)
    trajectories = (trx_v2e,trx_ej,trx_js)
    deltavs = (delv_e,delv_j,delv_s)
    times = (date_flyby_venus2,date_flyby_earth,date_flyby_jupiter,date_arrive_saturn)
    return (total_deltav,orbits,trajectories,deltavs,times)

def print_times(times):
    print("Venus:   ",times[0])
    print("Earth:   ",times[1])
    print("Jupiter: ",times[2])
    print("Saturn:  ",times[3])
    print("**")
    print("V-E: ", (times[1]-times[0]).to(u.year))
    print("E-J: ", (times[2]-times[1]).to(u.year))
    print("E-S: ", (times[3]-times[2]).to(u.year))
        



In [17]:
cassini_js_time.to(u.year).value

3.5017111567419574

In [22]:
t_guess_cassini = [27,cassini_js_time.to(u.year).value,cassini_ej_time.to(u.year).value,cassini_ve_time.to(u.year).value]
sol=trajectory_calculator(t=t_guess_cassini,plot_on=0,disp_on=1)

computed saturn
computed J-S
computed E-J
computed V-E
Total delta-v:  82.09792665510716 km / s


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2046-12-31 18:01:09.184. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-01 18:01:09.184. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2042-02-16 18:01:09.185. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2041-12-23 18:01:09.184. Use Time(..., scale='tdb') instead.



In [ ]:
sol=trajectory_calculator(tmod=[0,0,0,0],plot_on=0,disp_on=1)
if 1:
    op=OrbitPlotter2D()
    op.plot(sol[1][0],label='V')
    op.plot(sol[1][1],label='E')
    op.plot(sol[1][2],label='J')
    op.plot(sol[1][3],label='S')
    op.plot(sol[2][0],label='VE')
    op.plot(sol[2][1],label='EJ')
    op.plot(sol[2][2],label='JS')



/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-03-29 00:01:09.186. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-09-27 00:01:09.182. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2042-05-15 00:01:09.185. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2042-03-21 00:01:09.186. Use Time(..., scale='tdb') instead.



computed saturn
computed J-S
computed E-J
computed V-E
Total delta-v:  49.73689056630519 km / s


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/propagation.py:232: UserWarning:

Frame <class 'astropy.coordinates.builtin_frames.icrs.ICRS'> does not support 'obstime', time values were not returned



In [21]:
sol

(<Quantity 82.09792665510716 km / s>,
 (1 x 1 AU x 24.4 deg (ICRS) orbit around Sun (☉) at epoch 2041-12-23 18:01:09.184 (TDB),
  1 x 1 AU x 23.4 deg (ICRS) orbit around Sun (☉) at epoch 2042-02-16 18:01:09.185 (TDB),
  5 x 5 AU x 23.2 deg (ICRS) orbit around Sun (☉) at epoch 2043-07-01 18:01:09.184 (TDB),
  9 x 10 AU x 22.6 deg (ICRS) orbit around Sun (☉) at epoch 2046-12-31 18:01:09.184 (TDB)),
 (30293036 x -2883088647 km x 24.0 deg (HCRS) orbit around Sun (☉) at epoch 2041-12-23 18:00:00.000 (UTC),
  1 x 10 AU x 23.2 deg (HCRS) orbit around Sun (☉) at epoch 2042-02-16 18:00:00.000 (UTC),
  0 x 47 AU x 27.1 deg (HCRS) orbit around Sun (☉) at epoch 2043-07-01 18:00:00.000 (UTC)),
 (<Quantity 38.076032380696105 km / s>,
  <Quantity 29.27965312341461 km / s>,
  <Quantity 14.742241150996456 km / s>),
 (<Time object: scale='utc' format='iso' value=2041-12-23 18:00:00.000>,
  <Time object: scale='utc' format='iso' value=2042-02-16 18:00:00.000>,
  <Time object: scale='utc' format='iso' val

In [23]:
t_guess_cassini

[27, 3.5017111567419574, 1.3689253935660506, 0.15058179329226556]

In [26]:
bounds = ((27-5,27+5),(0.01,5),(0.01,5),(0.01,1))
options = {'maxiter': 30,'disp': True}

def total_deltav_calculator(tmod):
    print(tmod)
    sol=trajectory_calculator(tmod,plot_on=0,disp_on=0)
    
    return sol[0].to(u.km/u.s).value

opt_sol = opt.minimize(total_deltav_calculator,x0=t_guess_cassini,options=options,bounds=bounds)

opt_sol

[ 27.           3.50171116   1.36892539   0.15058179]
[ 27.00000001   3.50171116   1.36892539   0.15058179]
[ 27.           3.50171117   1.36892539   0.15058179]
[ 27.           3.50171116   1.3689254    0.15058179]
[ 27.           3.50171116   1.36892539   0.1505818 ]
[  3.20000000e+01   1.00000000e-02   1.00000000e-02   1.00000000e+00]
[  3.20000000e+01   1.00000000e-02   1.00000000e-02   1.00000000e+00]
[  3.20000000e+01   1.00000100e-02   1.00000000e-02   1.00000000e+00]
[  3.20000000e+01   1.00000000e-02   1.00000100e-02   1.00000000e+00]
[  3.20000000e+01   1.00000000e-02   1.00000000e-02   1.00000001e+00]
[ 28.75941787   2.27303536   0.89074187   0.44947811]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2046-12-31 18:01:09.184. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-01 18:01:09.184. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2042-02-16 18:01:09.185. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2041-12-23 18:01:09.184. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 28.75941788   2.27303536   0.89074187   0.44947811]
[ 28.75941787   2.27303537   0.89074187   0.44947811]
[ 28.75941787   2.27303536   0.89074188   0.44947811]
[ 28.75941787   2.27303536   0.89074187   0.44947812]
[ 27.416082     3.21114353   1.25584051   0.22126732]
[ 27.41608201   3.21114353   1.25584051   0.22126732]
[ 27.416082     3.21114354   1.25584051   0.22126732]
[ 27.416082     3.21114353   1.25584052   0.22126732]
[ 27.416082     3.21114353   1.25584051   0.22126733]
[ 28.4159158    2.51415369   0.99168391   0.18112024]
[ 28.41591581   2.51415369   0.99168391   0.18112024]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-23 06:03:52.992. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2048-05-31 21:56:14.032. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2045-11-25 14:51:57.585. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-11-28 09:45:53.288. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 28.4159158    2.5141537    0.99168391   0.18112024]
[ 28.4159158    2.51415369   0.99168392   0.18112024]
[ 28.4159158    2.51415369   0.99168391   0.18112025]
[ 27.66052213   3.04074292   1.19125931   0.21145213]
[ 27.66052214   3.04074292   1.19125931   0.21145213]
[ 27.66052213   3.04074293   1.19125931   0.21145213]
[ 27.66052213   3.04074292   1.19125932   0.21145213]
[ 27.66052213   3.04074292   1.19125931   0.21145214]
[ 27.83635796   2.91816676   1.14480339   0.20439166]
[ 27.83635797   2.91816676   1.14480339   0.20439166]
[ 27.83635796   2.91816677   1.14480339   0.20439166]
[ 27.83635796   2.91816676   1.1448034    0.20439166]
[ 27.83635796   2.91816676   1.14480339   0.20439167]
[ 27.68051482   3.0268059    1.18597723   0.21064935]
[ 27.68051483   3.0268059    1.18597723   0.21064935]

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-27 13:50:21.831. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-06 07:24:43.768. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-08-26 18:25:53.962. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-06-20 14:09:18.999. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 


[ 27.68051482   3.02680591   1.18597723   0.21064935]
[ 27.68051482   3.0268059    1.18597724   0.21064935]
[ 27.68051482   3.0268059    1.18597723   0.21064936]
[  3.05429127e+01   1.03193111e+00   4.27612984e-01   1.00000000e-02]
[  3.05429127e+01   1.03193111e+00   4.27612984e-01   1.00000000e-02]
[  3.05429127e+01   1.03193112e+00   4.27612984e-01   1.00000000e-02]
[  3.05429127e+01   1.03193111e+00   4.27612994e-01   1.00000000e-02]
[  3.05429127e+01   1.03193111e+00   4.27612984e-01   1.00000100e-02]
[ 27.84241532   2.9139735    1.14308328   0.19930039]
[ 27.84241533   2.9139735    1.14308328   0.19930039]
[ 27.84241532   2.91397351   1.14308328   0.19930039]

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2049-01-30 16:49:43.074. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2049-01-27 01:10:07.074. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-11-04 10:37:54.814. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-12-05 02:44:24.643. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 


[ 27.84241532   2.9139735    1.14308329   0.19930039]
[ 27.84241532   2.9139735    1.14308328   0.1993004 ]
[ 27.69233865   3.01856559   1.18284462   0.20982052]
[ 27.69233866   3.01856559   1.18284462   0.20982052]
[ 27.69233865   3.0185656    1.18284462   0.20982052]
[ 27.69233865   3.01856559   1.18284463   0.20982052]
[ 27.69233865   3.01856559   1.18284462   0.20982053]
[ 27.70291979   3.01311166   1.18335609   0.17491543]
[ 27.7029198    3.01311166   1.18335609   0.17491543]
[ 27.70291979   3.01311167   1.18335609   0.17491543]
[ 27.70291979   3.01311166   1.1833561    0.17491543]
[ 27.70291979   3.01311166   1.18335609   0.17491544]
[ 27.74524435   2.99129595   1.18540194   0.03529507]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-04 17:34:40.417. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-01 20:16:09.303. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-08 22:52:37.780. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-04 17:34:39.786. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.74524436   2.99129595   1.18540194   0.03529507]
[ 27.74524435   2.99129596   1.18540194   0.03529507]
[ 27.74524435   2.99129595   1.18540195   0.03529507]
[ 27.74524435   2.99129595   1.18540194   0.03529508]
[ 27.71490696   3.00693301   1.18393551   0.13537212]
[ 27.71490697   3.00693301   1.18393551   0.13537212]
[ 27.71490696   3.00693302   1.18393551   0.13537212]
[ 27.71490696   3.00693301   1.18393552   0.13537212]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-15 14:07:07.823. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-11 03:44:24.512. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-22 17:04:05.183. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-18 20:53:37.271. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.71490696   3.00693301   1.18393551   0.13537213]
[ 27.70810936   3.01043675   1.18360694   0.15779604]
[ 27.70810937   3.01043675   1.18360694   0.15779604]
[ 27.70810936   3.01043676   1.18360694   0.15779604]
[ 27.70810936   3.01043675   1.18360695   0.15779604]
[ 27.70810936   3.01043675   1.18360694   0.15779605]
[ 27.71097637   3.00895899   1.18374552   0.14833836]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-11 19:49:02.107. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-07 12:19:07.893. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-10 21:04:43.660. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-17 10:26:17.017. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.71097638   3.00895899   1.18374552   0.14833836]
[ 27.71097637   3.008959     1.18374552   0.14833836]
[ 27.71097637   3.00895899   1.18374553   0.14833836]
[ 27.71097637   3.00895899   1.18374552   0.14833837]
[  2.76641488e+01   3.04875524e+00   1.20866266e+00   2.51428619e-02]
[  2.76641489e+01   3.04875524e+00   1.20866266e+00   2.51428619e-02]
[  2.76641488e+01   3.04875525e+00   1.20866266e+00   2.51428619e-02]
[  2.76641488e+01   3.04875524e+00   1.20866267e+00   2.51428619e-02]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-08-12 18:33:34.438. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-29 07:25:21.710. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-20 03:01:13.332. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-08-31 07:56:53.033. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[  2.76641488e+01   3.04875524e+00   1.20866266e+00   2.51428719e-02]
[ 27.69842231   3.01962802   1.19042559   0.11531069]
[ 27.69842232   3.01962802   1.19042559   0.11531069]
[ 27.69842231   3.01962803   1.19042559   0.11531069]
[ 27.69842231   3.01962802   1.1904256    0.11531069]
[ 27.69842231   3.01962802   1.19042559   0.1153107 ]
[ 27.7093971    3.01030113   1.18458586   0.14418355]
[ 27.70939711   3.01030113   1.18458586   0.14418355]
[ 27.7093971    3.01030114   1.18458586   0.14418355]
[ 27.7093971    3.01030113   1.18458587   0.14418355]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-16 20:35:38.962. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-12 08:17:40.114. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-07 16:12:53.493. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-16 00:18:06.652. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.7093971    3.01030113   1.18458586   0.14418356]
[ 27.68115423   3.02995789   1.19199061   0.14923704]
[ 27.68115424   3.02995789   1.19199061   0.14923704]
[ 27.68115423   3.0299579    1.19199061   0.14923704]
[ 27.68115423   3.02995789   1.19199062   0.14923704]
[ 27.68115423   3.02995789   1.19199061   0.14923705]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-04-23 23:12:16.988. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-14 14:12:04.076. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-08 12:02:39.970. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-03 05:42:14.359. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.7031921    3.01461975   1.18621269   0.14529381]
[ 27.70319211   3.01461975   1.18621269   0.14529381]
[ 27.7031921    3.01461976   1.18621269   0.14529381]
[ 27.7031921    3.01461975   1.1862127    0.14529381]
[ 27.7031921    3.01461975   1.18621269   0.14529382]
[ 27.69898895   3.01742727   1.18695517   0.15179296]
[ 27.69898896   3.01742727   1.18695517   0.15179296]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-13 01:21:22.891. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-05 22:35:20.003. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-06-30 09:44:23.432. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-05 23:07:21.835. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.69898895   3.01742728   1.18695517   0.15179296]
[ 27.69898895   3.01742727   1.18695518   0.15179296]
[ 27.69898895   3.01742727   1.18695517   0.15179297]
[ 27.70230196   3.01521432   1.18636993   0.14667019]
[ 27.70230197   3.01521432   1.18636993   0.14667019]
[ 27.70230196   3.01521433   1.18636993   0.14667019]
[ 27.70230196   3.01521432   1.18636994   0.14667019]
[ 27.70230196   3.01521432   1.18636993   0.1466702 ]

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-14 06:23:53.825. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-07 23:01:46.392. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-02 15:18:38.605. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-10 01:35:59.361. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 


[ 27.70465368   3.01360379   1.18568845   0.14839511]
[ 27.70465369   3.01360379   1.18568845   0.14839511]
[ 27.70465368   3.0136038    1.18568845   0.14839511]
[ 27.70465368   3.01360379   1.18568846   0.14839511]
[ 27.70465368   3.01360379   1.18568845   0.14839512]
[ 27.70297927   3.01475048   1.18617366   0.14716698]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-14 12:20:07.719. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-08 09:01:58.005. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-03 03:02:04.056. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-10 08:58:07.457. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.70297928   3.01475048   1.18617366   0.14716698]
[ 27.70297927   3.01475049   1.18617366   0.14716698]
[ 27.70297927   3.01475048   1.18617367   0.14716698]
[ 27.70297927   3.01475048   1.18617366   0.14716699]
[ 27.70349055   3.01445189   1.18609897   0.14696976]
[ 27.70349056   3.01445189   1.18609897   0.14696976]
[ 27.70349055   3.0144519    1.18609897   0.14696976]
[ 27.70349055   3.01445189   1.18609898   0.14696976]
[ 27.70349055   3.01445189   1.18609897   0.14696977]
[ 27.70333729   3.01459376   1.18616987   0.14706078]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-10 18:27:05.563. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-14 15:28:25.900. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-08 13:32:41.932. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-03 07:34:47.654. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.7033373    3.01459376   1.18616987   0.14706078]
[ 27.70333729   3.01459377   1.18616987   0.14706078]
[ 27.70333729   3.01459376   1.18616988   0.14706078]
[ 27.70333729   3.01459376   1.18616987   0.14706079]
[ 27.70338721   3.01462448   1.18621853   0.14706659]
[ 27.70338722   3.01462448   1.18621853   0.14706659]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-14 15:54:41.352. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-08 13:42:47.919. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-03 07:19:18.019. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-10 14:08:09.273. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.70338721   3.01462449   1.18621853   0.14706659]
[ 27.70338721   3.01462448   1.18621854   0.14706659]
[ 27.70338721   3.01462448   1.18621853   0.1470666 ]
[ 27.7035869    3.01474736   1.18641317   0.14708986]
[ 27.70358691   3.01474736   1.18641317   0.14708986]
[ 27.7035869    3.01474737   1.18641317   0.14708986]
[ 27.7035869    3.01474736   1.18641318   0.14708986]
[ 27.7035869    3.01474736   1.18641317   0.14708987]
[ 27.70501366   3.01531572   1.18751319   0.14716367]
[ 27.70501367   3.01531572   1.18751319   0.14716367]
[ 27.70501366   3.01531573   1.18751319   0.14716367]
[ 27.70501366   3.01531572   1.1875132    0.14716367]
[ 27.70501366   3.01531572   1.18751319   0.14716368]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-08 21:54:40.978. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-03 04:10:14.763. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-10 10:08:02.592. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-15 06:10:08.600. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.71122232   3.01747604   1.19200722   0.14735048]
[ 27.71122233   3.01747604   1.19200722   0.14735048]
[ 27.71122232   3.01747605   1.19200722   0.14735048]
[ 27.71122232   3.01747604   1.19200723   0.14735048]
[ 27.71122232   3.01747604   1.19200722   0.14735049]
[ 27.72885231   3.02321303   1.20439445   0.14773887]
[ 27.72885232   3.02321303   1.20439445   0.14773887]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-09-14 17:39:11.456. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-02 19:55:53.007. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-09 20:51:08.690. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-09-23 23:08:19.206. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 27.72885231   3.02321304   1.20439445   0.14773887]
[ 27.72885231   3.02321303   1.20439446   0.14773887]
[ 27.72885231   3.02321303   1.20439445   0.14773888]
[ 27.78526892   3.04105916   1.24354732   0.14876902]
[ 27.78526893   3.04105916   1.24354732   0.14876902]
[ 27.78526892   3.04105917   1.24354732   0.14876902]
[ 27.78526892   3.04105916   1.24354733   0.14876902]
[ 27.78526892   3.04105916   1.24354732   0.14876903]
[ 27.96784804   3.09831826   1.36969045   0.15183521]
[ 27.96784805   3.09831826   1.36969045   0.15183521]
[ 27.96784804   3.09831827   1.36969045   0.15183521]
[ 27.96784804   3.09831826   1.36969046   0.15183521]
[ 27.96784804   3.09831826   1.36969045   0.15183522]
[ 28.40662402   3.23922604   1.66885938   0.15879965]
[ 28.40662403   3.23922604   1.66885938   0.15879965]
[ 28.40662402   3.23922605   1.66885938   0.15879965]
[ 28.40662402   3.23922604   1.66885939   0.15879965]
[ 28.40662402   3.23922604   1.66885938   0.15879966]
[ 28.92679717   3.41629944  

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-12-20 06:10:30.548. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2044-11-13 14:19:02.089. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-02 07:36:38.889. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-07 20:37:24.172. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 28.92679717   3.41629944   2.01714929   0.16305266]
[ 28.92679717   3.41629944   2.01714928   0.16305267]
[ 29.69193368   3.67419958   2.51872052   0.1815055 ]
[ 29.69193369   3.67419958   2.51872052   0.1815055 ]
[ 29.69193368   3.67419959   2.51872052   0.1815055 ]
[ 29.69193368   3.67419958   2.51872053   0.1815055 ]
[ 29.69193368   3.67419958   2.51872052   0.18150551]
[ 29.83763949   3.72729332   2.61732792   0.17747019]
[ 29.8376395    3.72729332   2.61732792   0.17747019]
[ 29.83763949   3.72729333   2.61732792   0.17747019]
[ 29.83763949   3.72729332   2.61732793   0.17747019]
[ 29.83763949   3.72729332   2.61732792   0.1774702 ]
[ 29.97172533   3.77746247   2.70530299   0.17394265]
[ 29.97172534   3.77746247   2.70530299   0.17394265]
[ 29.97172533   3.77746248   2.70530299   0.17394265]
[ 29.97172533   3.77746247   2.705303     0.17394265]
[ 29.97172533   3.77746247   2.70530299   0.17394266]
[ 30.15028346   3.84266989   2.81775294   0.17307239]
[ 30.15028347   3.84266989  

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-04-25 19:27:36.382. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2049-12-21 04:09:48.627. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2046-03-12 10:55:38.945. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-06-28 08:14:29.232. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 30.86964438   4.10795598   3.24534509   0.16894388]
[ 30.86964437   4.10795599   3.24534509   0.16894388]
[ 30.86964437   4.10795598   3.2453451    0.16894388]
[ 30.86964437   4.10795598   3.24534509   0.16894389]
[ 31.68389257   4.41540588   3.62231543   0.15022239]
[ 31.68389258   4.41540588   3.62231543   0.15022239]
[ 31.68389257   4.41540589   3.62231543   0.15022239]
[ 31.68389257   4.41540588   3.62231544   0.15022239]
[ 31.68389257   4.41540588   3.62231543   0.1502224 ]
[ 32.           4.52309086   3.80325601   0.16494153]
[ 32.00000001   4.52309086   3.80325601   0.16494153]
[ 32.           4.52309087   3.80325601   0.16494153]
[ 32.           4.52309086   3.80325602   0.16494153]
[ 32.           4.52309086   3.80325601   0.16494154]
[ 32.           4.52779733   3.69804006   0.15828886]
[ 32.00000001   4.52779733   3.69804006   0.15828886]
[ 32.           4.52779734   3.69804006   0.15828886]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-05-07 15:19:20.825. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2051-09-07 13:01:17.418. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-04-08 19:34:24.922. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-08-24 18:21:23.593. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 32.           4.52779733   3.69804007   0.15828886]
[ 32.           4.52779733   3.69804006   0.15828887]
[ 32.           4.52353572   3.79331093   0.16431272]
[ 32.00000001   4.52353572   3.79331093   0.16431272]
[ 32.           4.52353573   3.79331093   0.16431272]
[ 32.           4.52353572   3.79331094   0.16431272]
[ 32.           4.52353572   3.79331093   0.16431273]
[ 32.           4.52325613   3.79956118   0.16470791]
[ 32.00000001   4.52325613   3.79956118   0.16470791]
[ 32.           4.52325614   3.79956118   0.16470791]
[ 32.           4.52325613   3.79956119   0.16470791]
[ 32.           4.52325613   3.79956118   0.16470792]
[ 32.           5.           4.72692104   0.1613902 ]
[ 32.00000001   5.           4.72692104   0.1613902 ]
[ 32.           5.00000001   4.72692104   0.1613902 ]
[ 32.           5.           4.72692105   0.1613902 ]
[ 32.           5.           4.72692104   0.16139021]
[ 32.           4.52430721   3.80160574   0.1647006 ]
[ 32.00000001   4.52430721  

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-06-23 11:56:31.520. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-09-03 23:03:58.363. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-05 19:18:02.750. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-06-23 19:42:21.837. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 32.           4.52430722   3.80160574   0.1647006 ]
[ 32.           4.52430721   3.80160575   0.1647006 ]
[ 32.           4.52430721   3.80160574   0.16470061]
[ 32.           4.52342153   3.79988291   0.16470676]
[ 32.00000001   4.52342153   3.79988291   0.16470676]
[ 32.           4.52342154   3.79988291   0.16470676]
[ 32.           4.52342153   3.79988292   0.16470676]
[ 32.           4.52342153   3.79988291   0.16470677]
[ 32.           4.5271505    3.79157583   0.15764393]
[ 32.00000001   4.5271505    3.79157583   0.15764393]
[ 32.           4.52715051   3.79157583   0.15764393]
[ 32.           4.5271505    3.79157584   0.15764393]
[ 32.           4.5271505    3.79157583   0.15764394]
[ 32.           4.52409481   3.79838305   0.16343155]
[ 32.00000001   4.52409481   3.79838305   0.16343155]
[ 32.           4.52409482   3.79838305   0.16343155]
[ 32.           4.52409481   3.79838306   0.16343155]
[ 32.           4.52409481   3.79838305   0.16343156]
[ 32.           4.52449952  

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-06-23 13:48:14.906. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-09-05 05:10:42.039. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-07 12:32:14.533. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-06-23 13:48:15.221. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

[ 32.00000001   4.52449952   3.79788952   0.16331697]
[ 32.           4.52449953   3.79788952   0.16331697]
[ 32.           4.52449952   3.79788953   0.16331697]
[ 32.           4.52449952   3.79788952   0.16331698]
[ 32.           4.52516642   3.79722668   0.16326178]
[ 32.00000001   4.52516642   3.79722668   0.16326178]
[ 32.           4.52516643   3.79722668   0.16326178]
[ 32.           4.52516642   3.79722669   0.16326178]
[ 32.           4.52516642   3.79722668   0.16326179]


/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-06-23 04:24:37.302. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-09-05 05:55:16.552. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-07 14:46:06.732. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-06-23 04:24:37.618. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to 

      fun: 19.204786918664688
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([ -0.95352988,  -4.63682071,   1.18568479, -21.55289671])
  message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
     nfev: 265
      nit: 30
   status: 1
  success: False
        x: array([ 32.        ,   4.52516642,   3.79722668,   0.16326178])

In [27]:
t_guess_cassini

[27, 3.5017111567419574, 1.3689253935660506, 0.15058179329226556]

In [ ]:

options = {'maxiter': 30,'disp': False}
opt_sol = opt.minimize(total_deltav_calculator,x0=opt_sol.x,options=options)
opt_sol

In [28]:
opt_sol

      fun: 19.204786918664688
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([ -0.95352988,  -4.63682071,   1.18568479, -21.55289671])
  message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
     nfev: 265
      nit: 30
   status: 1
  success: False
        x: array([ 32.        ,   4.52516642,   3.79722668,   0.16326178])

In [30]:
sol=trajectory_calculator(t=opt_sol.x,plot_on=0,disp_on=0)

print("Tmod: ",opt_sol.x)
print()
print("Total deltav: ", sol[0])
print("Delta vs: ",[x.value for x in sol[3]])
print()

print('Times:')
print_times(sol[4])
print()
t_ve=sol[4][1]-sol[4][0]
t_ej=sol[4][2]-sol[4][1]
t_js=sol[4][3]-sol[4][2]


trx_ve = sol[2][0]
trx_ej = sol[2][1]
trx_js = sol[2][2]


trx_ve_half = trx_ve.propagate(t_ve/2)
trx_ej_half = trx_ej.propagate(t_ej/2)
trx_js_half = trx_js.propagate(t_ej/2)


op=OrbitPlotter2D()
op.plot(sol[1][0],label='V')
op.plot(sol[1][1],label='E')
op.plot(sol[1][2],label='J')
op.plot(sol[1][3],label='S')
op.plot(trx_ve_half,label='VE')
op.plot(trx_ej_half,label='EJ')
op.plot(trx_js_half,label='JS')

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2052-01-01 00:01:09.184. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-06-23 04:24:37.302. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-09-05 05:55:16.552. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2043-07-07 14:46:06.732. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/propagation.py:232: UserWarning:

Frame <class 'astropy.coord

Tmod:  [ 32.           4.52516642   3.79722668   0.16326178]

Total deltav:  19.204786918664688 km / s
Delta vs:  [0.5790827206586804, 8.43114315329468, 10.194561044711325]

Times:
Venus:    2043-07-07 14:44:57.548
Earth:    2043-09-05 05:54:07.370
Jupiter:  2047-06-23 04:23:28.118
Saturn:   2052-01-01 00:00:00.000
**
V-E:  0.16326177595941857 yr
E-J:  3.7972266822614382 yr
E-S:  4.525166422109325 yr



FigureWidget({
    'data': [{'hoverinfo': 'none',
              'line': {'color': 'rgb(31, 119, 180)', 'dash':…

In [36]:
tmod = opt_sol.x
tmod = [27.238877,4.798,1.2879,0.1313]
sol=trajectory_calculator(t=tmod,plot_on=0,disp_on=0)

print("Tmod: ",opt_sol.x)
print()
print("Total deltav: ", sol[0])
print("Delta vs: ",[x.value for x in sol[3]])
print()

print('Times:')
print_times(sol[4])
print()
t_ve=sol[4][1]-sol[4][0]
t_ej=sol[4][2]-sol[4][1]
t_js=sol[4][3]-sol[4][2]


trx_ve = sol[2][0]
trx_ej = sol[2][1]
trx_js = sol[2][2]


trx_ve_half = trx_ve.propagate(t_ve/2)
trx_ej_half = trx_ej.propagate(t_ej/2)
trx_js_half = trx_js.propagate(t_ej/2)


op=OrbitPlotter2D()
op.plot(sol[1][0],label='V')
op.plot(sol[1][1],label='E')
op.plot(sol[1][2],label='J')
op.plot(sol[1][3],label='S')
op.plot(trx_ve_half,label='VE')
op.plot(trx_ej_half,label='EJ')
op.plot(trx_js_half,label='JS')

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2047-03-29 00:00:54.001. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2042-06-10 12:44:49.200. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2041-02-25 03:00:56.161. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py:389: TimeScaleWarning:

Input time was converted to scale='tdb' with value 2041-01-08 04:02:23.279. Use Time(..., scale='tdb') instead.

/Users/Devansh/anaconda3/lib/python3.6/site-packages/poliastro/twobody/propagation.py:232: UserWarning:

Frame <class 'astropy.coord

Tmod:  [ 32.           4.52516642   3.79722668   0.16326178]

Total deltav:  6.010478813049802 km / s
Delta vs:  [0.19207023597361006, 0.0776495284180622, 5.74075904865813]

Times:
Venus:    2041-01-08 04:01:14.095
Earth:    2041-02-25 02:59:46.975
Jupiter:  2042-06-10 12:43:40.015
Saturn:   2047-03-28 23:59:44.815
**
V-E:  0.1313 yr
E-J:  1.2879 yr
E-S:  4.798 yr



FigureWidget({
    'data': [{'hoverinfo': 'none',
              'line': {'color': 'rgb(31, 119, 180)', 'dash':…

In [ ]:
t_ve

In [ ]:
trx_ve = sol[2][0]

In [ ]:
import poliastro.twobody.propagation as Propagation

In [ ]:
trx_ve_half = trx_ve.propagate(t_ve/2)

In [ ]:
trx_ve_half.plot()

In [ ]:
norm(o_e.v.to(u.km/u.s))

In [ ]:
print_times(sol[4])

In [ ]:
o_e

In [34]:
(Time("2047-03-29", scale="utc")-Time("2020-01-01", scale="utc")).to(u.year)

<Quantity 27.238877481177276 yr>